version: '3'

services:
  db:
    image: postgres:15
    container_name: skeletonDB 
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: